// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "ELBIS",
//   description: "Generated by create next app",
//   icons: {
//     icon: "assets/logo.svg", 
//   },
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <link rel="icon" href="assets/logo.svg" type="image/svg+xml" />
//         {/* Include Leaflet CSS */}
//         <link
//           rel="stylesheet"
//           href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
//         />
//         {/* Include Leaflet JS */}
//         <script
//           src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
//           defer
//         ></script>
//       </head>
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";  // Import Poppins
import "./globals.css";

// Load both Inter and Poppins fonts
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "ELBIS",
  description: "Generated by create next app",
  icons: {
    icon: "assets/logo.svg", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="assets/logo.svg" type="image/svg+xml" />
        {/* Include Leaflet CSS */}
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
        />
        {/* Include Leaflet JS */}
        <script
          src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
          defer
        ></script>
      </head>
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  );
}
